name: Update wakatime stats

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    name: Update-waka-stats
    runs-on: ubuntu-latest
    env:
      GH_USER: sljeff
      README: README.md
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 71273c536e134e0906f5d6a7f47795ca
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Update gist
        uses: matchai/waka-box@master
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Edit README
        run: |
          python update_readme.py
          git config --global user.email "bot@github.com" && git config --global user.name "Waka-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull && git push
